### ISSUE TITLE
Break out jwt signing in a separate module

### ISSUE THREAD

**Issue by jbygdell** [neicnordic/sda-auth#116]
The current codebase have one jwt function in the EGA module and one in the Elixir module, we only need one.

**Comment by dbampalikis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sensitive-Data-Archive-6041ec3fd9297d0016321f73/issues/neicnordic/sda-auth/116?planning-poker) with Zenhub @aaperis @jbygdell @kostas-kou @norling @viklund @shreyasshivakumara
